name: Deploy to Lolipop Server

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo, pdo_mysql, mbstring
        
    - name: Validate PHP files
      run: |
        find . -name "*.php" -exec php -l {} \;
        
    - name: Create deployment package
      run: |
        # 不要なファイルを除外してアーカイブ作成
        tar --exclude='.git' \
            --exclude='.github' \
            --exclude='node_modules' \
            --exclude='*.log' \
            --exclude='*.bat' \
            --exclude='*.ps1' \
            --exclude='setup_database.*' \
            --exclude='check_environment.*' \
            --exclude='backup_database.*' \
            --exclude='.htaccess.new' \
            --exclude='backups' \
            --exclude='*.tmp' \
            -czf quiz_tool_deploy.tar.gz .
            
    - name: Deploy to Lolipop via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
        server-dir: /
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/*.log
          **/*.bat
          **/*.ps1
          **/setup_database.*
          **/check_environment.*
          **/backup_database.*
          **/.htaccess.new
          **/backups/**
          **/*.tmp
          **/README.md
          
    - name: Notification
      if: always()
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Deployment successful!"
        else
          echo "❌ Deployment failed!"
        fi
